### ISSUE TITLE
Fix issues with killing players

### ISSUE THREAD

**Issue by LeskovarLukas** [AmongHTBLuVA/AmongHTL#21]
1. notify a player when he gets killed
2. prevent players from "coming back" by reloading the page
3. make the player move as a spectator after being killed (but other players can't see him)

**Comment by Kleinrad** [comment]
fixed 2., but the dead player is still moved after the reload

**Comment by Kleinrad** [comment]
added 3.

**Comment by Kleinrad** [comment]
fixed dead player moved reload

**Comment by Kleinrad** [comment]
problem when other players move. Phantom player view gets set to the corpse
