### ISSUE TITLE
Player position not recognised 

### ISSUE THREAD

**Issue by LeskovarLukas** [AmongHTBLuVA/AmongHTL#4]
![](https://user-images.githubusercontent.com/44904007/119405379-74501180-bce1-11eb-836d-ee418928f1f2.png)

When multiple players join the same lobby this bug happens.
In this scenario, the exception occurred right after the map was loaded.

**Comment by Kleinrad** [comment]
please try to reproduce, i don't really know if I fixed it, only that for me everything worked fine after changing a few lines

**Comment by Kleinrad** [comment]
Problem occurs when players are in a game and the server restarts. When a player moves after the server restarted the room is undefined and the exception gets thrown

possible fix: kick players from game after timeout

**Comment by LeskovarLukas** [comment]
is this still relevant?
